### ISSUE TITLE
Remove need for Slackey constructor?

### ISSUE THREAD

**Issue by FredKSchott** [FredKSchott/slackey#11]
Currently, Slackey is constructor that initializes custom SDK objects with the proper configuration values like client ID & secret. I expected these would be more important to the library, but they're really only needed by the getAccessToken method. 

I'm thinking of pulling all that out into a seperate "Oauth Client" just like the Web & Webhook clients. It would be initialized with ID & Secret, and then called with an access token.

```js
//Today
var Slackey = require('slackey');
var slackAPI = new Slackey({
  clientID: 'XXX',
  clientSecret: 'XXX',
});
var slackAPIClient = slackAPI.getAPIClient(//...
slackAPI.getAccessToken(options, callback);
```
```js
// Proposal
var slackey = require('slackey');
var slackAPIClient = slackey.getAPIClient(//...
var slackOAuthClient = slackey.getOAuthClient({
  clientID: 'XXX',
  clientSecret: 'XXX',
});
slackOAuthClient.call(options, callback);
```

Thoughts?

**Comment by jkresner** [comment]
Yeah this was initially confusing and a time sync. Especially because there were some strange nuances of the this context that was not correctly maintaining the baseUrl.
